### ISSUE TITLE
How is the dataset structured?

### ISSUE THREAD

**Issue by wizofe** [ygCoconut/MRIreconUNET#1]
Hi and thanks for the great code. Some interesting ideas with classes and using `fastai` here. Is there any way that you could give a bit more information about the dataset you’re using and how is it structured? Thanks!

**Comment by ygCoconut** [comment]
Hi Ioannis, thanks for your message ! 

The data I fed was a 3D numpy array, where you have cardiac slices (image space) at 20 different timepoints in one batch (time was the 3rd dimension). My input was undersampled NUFFT radial data (ca. 12 times undersampled). A whole heart (ca. 12 slices) was scanned in one breath instead of 1 breath per slice. The target was Cartesian fully sampled (1 breath per slice) data.

Curious to know about your ideas, thanks for your feedback!

## Updated my message ##

**Comment by wizofe** [comment]
Hi, Nils (hope that's right:))! 

Thanks for the detailed information. Unfortunately, the `data` folder in the repo is currently empty, so I couldn't find any example dataset to look at!

My problem is more on the 'MRI image reconstruction' space rather than volume reconstruction but as I am using 3D data, any inspiration is important. If I can get it working with the right data, I will happily provide feedback! Thank you :)

**Comment by ygCoconut** [comment]
Yes the data is not publicly available unfortunately. Are you looking to reconstruct a dataset from the k-space to the image space at first, or are you already in image space and trying to improve image quality with postprocessing ?

**Comment by ygCoconut** [comment]
FYI, I got the information that **publicly available datasets** are available at the following links:

https://legacy.openfmri.org/

https://openneuro.org/

https://fastmri.med.nyu.edu/

http://mridata.org/
